# Rebuild: 2/3/19 9:37AM
# Site Settings
title: Start Jekyll
subtitle: testing
author: Cody Taylor
license: CC BY
email: codyalantaylor@gmail.com
description: >
  A guide to getting started with Jekyll.
keywords: "word1, word2, word3"
baseurl: ""
twitter_username: OKCody_
github_username:  OKCody
theme_color: "#FFFFFF"
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
remote_theme: OKCody/Theme
id: content
# Build Settings
include:
  - _pages
  - sw.js
kramdown:
  input: GFM
defaults:
  -
    scope:
      path: ""
    values:
      layout: "toc"
  -
    scope:
      path: "_pages"
    values:
      layout: "pages"
